// import 'datatables.net-bs/css/dataTables.bootstrap.css'
// import 'datatables.net-responsive-bs/css/responsive.bootstrap.css'
// import 'datatables.net-buttons-bs/css/buttons.bootstrap.css'
// import 'datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.css'
// import 'datatables.net-fixedcolumns-bs/css/fixedColumns.bootstrap.css'

import '../globals'

import 'jszip'
// import 'pdfmake'
import 'datatables.net-bs'
import 'datatables.net-autofill'
import 'datatables.net-autofill-bs'
import 'datatables.net-buttons-bs'
import 'datatables.net-buttons/js/buttons.colVis.js'
import 'datatables.net-buttons/js/buttons.flash.js'
import 'datatables.net-buttons/js/buttons.html5.js'
import 'datatables.net-buttons/js/buttons.print.js'
import 'datatables.net-colreorder-bs'
import 'datatables.net-fixedcolumns-bs'
import 'datatables.net-fixedheader-bs'
import 'datatables.net-keytable'
import 'datatables.net-responsive-bs'
import 'datatables.net-rowgroup'
import 'datatables.net-rowreorder-bs'
import 'datatables.net-scroller-bs'
import 'datatables.net-select-bs'

